language: node_js

compiler: gcc
sudo: false
os: linux

node_js:
  - "8"
  - "10"
  - "12"
  - "13"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install:
  - export CC="gcc-4.9";
  - export CXX="g++-4.9";
  - export LINK="gcc-4.9";
  - export LINKXX="g++-4.9";
